version: "3"
services:

  hoc_proxy:
    build: .
    volumes:
      - ./havenofcode.template:/app/havenofcode.template
    ports:
      - 80:80
    environment:
      - HOC_PROXY_PORT=80
      - HOC_PROXY_HOST=havenofcode.com
      - HOC_HAVENOFCODE_HTTP_PORT=80
      - HOC_HAVENOFCODE_HTTP_HOST=network_hoc
    depends_on:
      - hoc_php
    networks:
      network_hoc:

  hoc_php:
    build: ../havenofcode
    ports:
      - 8081:80
    environment:
      - "HOC_GITHUB_CLIENT=ceebce24d13198175869"
      - "HOC_MYSQL_HOST=legacy-havenofcode.cem5dcxo5hdt.us-west-2.rds.amazonaws.com"
      - "HOC_GITHUB_SECRET=0cbf82e7605c575121be56dd5922ca8045bba98f"
      - "HOC_MYSQL_NAME=havenofc"
      - "HOC_MYSQL_USER"
      - "HOC_MYSQL_PASS"
    volumes:
      - ../havenofcode:/srv/http
    networks:
      network_hoc:
        aliases:
          - network_hoc

networks:
  network_hoc: